language: go

go:
- "1.x"
- "1.8.x"
- "1.9.x"
- "1.10.x"
- "master"

addons:
  postgresql: "10" # Use an up-to-date version of Postgres; default is 9.2.

services:
- postgresql # Needed for model tests.

before_script:
- psql -U postgres -c 'create database meow_test;'

env:
- MEOW_TEST_DB: postgres://localhost/meow_test?sslmode=disable

# Run with the race detector, it makes it slower, but races in something like this are bad.
script: go test -race ./...
