branches:
  except:
    # Exclude bors staging branches
    - /\.tmp$/

language: go

go:
- "1.x"
- "1.12.x"
- "1.13.x"

addons:
  postgresql: "9.6" # Use an up-to-date version of Postgres; default is 9.2.

services:
- postgresql # Needed for model tests.

env:
- MEOW_TEST_DB: postgres://localhost/meow_test?sslmode=disable

before_script:
- psql -U postgres -c 'create database meow_test;'



# Why aren't test dependencies installed by default e_e
# Passing -u so that we can use a cache and pull updates when needed, let's be nice to the hosts.
install: go get -t -u -v ./...

# Run with the race detector, it makes it slower, but races in something like this are bad.
script: go test -race ./...



# Cache $GOPATH/src to avoid having to re-fetch everything.
cache:
  directories:
  - $GOPATH/src

# Do not cache our own sources, that would be silly.
before_cache:
- ( shopt -s dotglob && rm -rf $GOPATH/src/github.com/meowpub/meow/* )
