// GENERATED FILE, DO NOT EDIT.
// Please refer to: tools/nsgen/templates.go
package ns

import (
	"github.com/meowpub/meow/ld/ns/as"
	"github.com/meowpub/meow/ld/ns/ldp"
	"github.com/meowpub/meow/ld/ns/meta"
	"github.com/meowpub/meow/ld/ns/owl"
	"github.com/meowpub/meow/ld/ns/rdf"
	"github.com/meowpub/meow/ld/ns/sec"
)

var Namespaces = map[string]*meta.Namespace{
	"http://www.w3.org/1999/02/22-rdf-syntax-ns#": rdf.RDF,
	"http://www.w3.org/2000/01/rdf-schema#":       rdf.RDFS,
	"http://www.w3.org/2002/07/owl#":              owl.OWL,
	"http://www.w3.org/ns/activitystreams#":       as.AS,
	"http://www.w3.org/ns/ldp#":                   ldp.LDP,
	"https://w3id.org/security#":                  sec.SEC,
}

var Classes = map[string]*meta.Type{
	"http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt":                   rdf.Class_Alt,
	"http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag":                   rdf.Class_Bag,
	"http://www.w3.org/1999/02/22-rdf-syntax-ns#List":                  rdf.Class_List,
	"http://www.w3.org/1999/02/22-rdf-syntax-ns#Property":              rdf.Class_Property,
	"http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq":                   rdf.Class_Seq,
	"http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement":             rdf.Class_Statement,
	"http://www.w3.org/2000/01/rdf-schema#Class":                       rdf.Class_Class,
	"http://www.w3.org/2000/01/rdf-schema#Container":                   rdf.Class_Container,
	"http://www.w3.org/2000/01/rdf-schema#ContainerMembershipProperty": rdf.Class_ContainerMembershipProperty,
	"http://www.w3.org/2000/01/rdf-schema#Datatype":                    rdf.Class_Datatype,
	"http://www.w3.org/2000/01/rdf-schema#Literal":                     rdf.Class_Literal,
	"http://www.w3.org/2000/01/rdf-schema#Resource":                    rdf.Class_Resource,
	"http://www.w3.org/2002/07/owl#AllDifferent":                       owl.Class_AllDifferent,
	"http://www.w3.org/2002/07/owl#AllDisjointClasses":                 owl.Class_AllDisjointClasses,
	"http://www.w3.org/2002/07/owl#AllDisjointProperties":              owl.Class_AllDisjointProperties,
	"http://www.w3.org/2002/07/owl#Annotation":                         owl.Class_Annotation,
	"http://www.w3.org/2002/07/owl#AnnotationProperty":                 owl.Class_AnnotationProperty,
	"http://www.w3.org/2002/07/owl#AsymmetricProperty":                 owl.Class_AsymmetricProperty,
	"http://www.w3.org/2002/07/owl#Axiom":                              owl.Class_Axiom,
	"http://www.w3.org/2002/07/owl#Class":                              owl.Class_Class,
	"http://www.w3.org/2002/07/owl#DataRange":                          owl.Class_DataRange,
	"http://www.w3.org/2002/07/owl#DatatypeProperty":                   owl.Class_DatatypeProperty,
	"http://www.w3.org/2002/07/owl#DeprecatedClass":                    owl.Class_DeprecatedClass,
	"http://www.w3.org/2002/07/owl#DeprecatedProperty":                 owl.Class_DeprecatedProperty,
	"http://www.w3.org/2002/07/owl#FunctionalProperty":                 owl.Class_FunctionalProperty,
	"http://www.w3.org/2002/07/owl#InverseFunctionalProperty":          owl.Class_InverseFunctionalProperty,
	"http://www.w3.org/2002/07/owl#IrreflexiveProperty":                owl.Class_IrreflexiveProperty,
	"http://www.w3.org/2002/07/owl#NamedIndividual":                    owl.Class_NamedIndividual,
	"http://www.w3.org/2002/07/owl#NegativePropertyAssertion":          owl.Class_NegativePropertyAssertion,
	"http://www.w3.org/2002/07/owl#Nothing":                            owl.Class_Nothing,
	"http://www.w3.org/2002/07/owl#ObjectProperty":                     owl.Class_ObjectProperty,
	"http://www.w3.org/2002/07/owl#Ontology":                           owl.Class_Ontology,
	"http://www.w3.org/2002/07/owl#OntologyProperty":                   owl.Class_OntologyProperty,
	"http://www.w3.org/2002/07/owl#ReflexiveProperty":                  owl.Class_ReflexiveProperty,
	"http://www.w3.org/2002/07/owl#Restriction":                        owl.Class_Restriction,
	"http://www.w3.org/2002/07/owl#SymmetricProperty":                  owl.Class_SymmetricProperty,
	"http://www.w3.org/2002/07/owl#Thing":                              owl.Class_Thing,
	"http://www.w3.org/2002/07/owl#TransitiveProperty":                 owl.Class_TransitiveProperty,
	"http://www.w3.org/ns/activitystreams#Accept":                      as.Class_Accept,
	"http://www.w3.org/ns/activitystreams#Activity":                    as.Class_Activity,
	"http://www.w3.org/ns/activitystreams#Add":                         as.Class_Add,
	"http://www.w3.org/ns/activitystreams#Announce":                    as.Class_Announce,
	"http://www.w3.org/ns/activitystreams#Application":                 as.Class_Application,
	"http://www.w3.org/ns/activitystreams#Arrive":                      as.Class_Arrive,
	"http://www.w3.org/ns/activitystreams#Article":                     as.Class_Article,
	"http://www.w3.org/ns/activitystreams#Audio":                       as.Class_Audio,
	"http://www.w3.org/ns/activitystreams#Block":                       as.Class_Block,
	"http://www.w3.org/ns/activitystreams#Collection":                  as.Class_Collection,
	"http://www.w3.org/ns/activitystreams#CollectionPage":              as.Class_CollectionPage,
	"http://www.w3.org/ns/activitystreams#Create":                      as.Class_Create,
	"http://www.w3.org/ns/activitystreams#Delete":                      as.Class_Delete,
	"http://www.w3.org/ns/activitystreams#Dislike":                     as.Class_Dislike,
	"http://www.w3.org/ns/activitystreams#Document":                    as.Class_Document,
	"http://www.w3.org/ns/activitystreams#Event":                       as.Class_Event,
	"http://www.w3.org/ns/activitystreams#Flag":                        as.Class_Flag,
	"http://www.w3.org/ns/activitystreams#Follow":                      as.Class_Follow,
	"http://www.w3.org/ns/activitystreams#Group":                       as.Class_Group,
	"http://www.w3.org/ns/activitystreams#Ignore":                      as.Class_Ignore,
	"http://www.w3.org/ns/activitystreams#Image":                       as.Class_Image,
	"http://www.w3.org/ns/activitystreams#IntransitiveActivity":        as.Class_IntransitiveActivity,
	"http://www.w3.org/ns/activitystreams#Invite":                      as.Class_Invite,
	"http://www.w3.org/ns/activitystreams#Join":                        as.Class_Join,
	"http://www.w3.org/ns/activitystreams#Leave":                       as.Class_Leave,
	"http://www.w3.org/ns/activitystreams#Like":                        as.Class_Like,
	"http://www.w3.org/ns/activitystreams#Link":                        as.Class_Link,
	"http://www.w3.org/ns/activitystreams#Listen":                      as.Class_Listen,
	"http://www.w3.org/ns/activitystreams#Mention":                     as.Class_Mention,
	"http://www.w3.org/ns/activitystreams#Move":                        as.Class_Move,
	"http://www.w3.org/ns/activitystreams#Note":                        as.Class_Note,
	"http://www.w3.org/ns/activitystreams#Object":                      as.Class_Object,
	"http://www.w3.org/ns/activitystreams#Offer":                       as.Class_Offer,
	"http://www.w3.org/ns/activitystreams#OrderedCollection":           as.Class_OrderedCollection,
	"http://www.w3.org/ns/activitystreams#OrderedCollectionPage":       as.Class_OrderedCollectionPage,
	"http://www.w3.org/ns/activitystreams#OrderedItems":                as.Class_OrderedItems,
	"http://www.w3.org/ns/activitystreams#Organization":                as.Class_Organization,
	"http://www.w3.org/ns/activitystreams#Page":                        as.Class_Page,
	"http://www.w3.org/ns/activitystreams#Person":                      as.Class_Person,
	"http://www.w3.org/ns/activitystreams#Place":                       as.Class_Place,
	"http://www.w3.org/ns/activitystreams#Profile":                     as.Class_Profile,
	"http://www.w3.org/ns/activitystreams#Question":                    as.Class_Question,
	"http://www.w3.org/ns/activitystreams#Read":                        as.Class_Read,
	"http://www.w3.org/ns/activitystreams#Reject":                      as.Class_Reject,
	"http://www.w3.org/ns/activitystreams#Relationship":                as.Class_Relationship,
	"http://www.w3.org/ns/activitystreams#Remove":                      as.Class_Remove,
	"http://www.w3.org/ns/activitystreams#Service":                     as.Class_Service,
	"http://www.w3.org/ns/activitystreams#TentativeAccept":             as.Class_TentativeAccept,
	"http://www.w3.org/ns/activitystreams#TentativeReject":             as.Class_TentativeReject,
	"http://www.w3.org/ns/activitystreams#Tombstone":                   as.Class_Tombstone,
	"http://www.w3.org/ns/activitystreams#Travel":                      as.Class_Travel,
	"http://www.w3.org/ns/activitystreams#Undo":                        as.Class_Undo,
	"http://www.w3.org/ns/activitystreams#Update":                      as.Class_Update,
	"http://www.w3.org/ns/activitystreams#Video":                       as.Class_Video,
	"http://www.w3.org/ns/activitystreams#View":                        as.Class_View,
	"http://www.w3.org/ns/ldp#BasicContainer":                          ldp.Class_BasicContainer,
	"http://www.w3.org/ns/ldp#Container":                               ldp.Class_Container,
	"http://www.w3.org/ns/ldp#DirectContainer":                         ldp.Class_DirectContainer,
	"http://www.w3.org/ns/ldp#IndirectContainer":                       ldp.Class_IndirectContainer,
	"http://www.w3.org/ns/ldp#NonRDFSource":                            ldp.Class_NonRDFSource,
	"http://www.w3.org/ns/ldp#Page":                                    ldp.Class_Page,
	"http://www.w3.org/ns/ldp#PageSortCriterion":                       ldp.Class_PageSortCriterion,
	"http://www.w3.org/ns/ldp#RDFSource":                               ldp.Class_RDFSource,
	"http://www.w3.org/ns/ldp#Resource":                                ldp.Class_Resource,
	"https://w3id.org/security#Digest":                                 sec.Class_Digest,
	"https://w3id.org/security#EncryptedMessage":                       sec.Class_EncryptedMessage,
	"https://w3id.org/security#GraphSignature2012":                     sec.Class_GraphSignature2012,
	"https://w3id.org/security#Key":                                    sec.Class_Key,
	"https://w3id.org/security#LinkedDataSignature2015":                sec.Class_LinkedDataSignature2015,
	"https://w3id.org/security#LinkedDataSignature2016":                sec.Class_LinkedDataSignature2016,
	"https://w3id.org/security#Signature":                              sec.Class_Signature,
}
