// Code generated by MockGen. DO NOT EDIT.
// Source: refreshtoken.go

// Package models is a generated GoMock package.
package models

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRefreshTokenStore is a mock of RefreshTokenStore interface
type MockRefreshTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenStoreMockRecorder
}

// MockRefreshTokenStoreMockRecorder is the mock recorder for MockRefreshTokenStore
type MockRefreshTokenStoreMockRecorder struct {
	mock *MockRefreshTokenStore
}

// NewMockRefreshTokenStore creates a new mock instance
func NewMockRefreshTokenStore(ctrl *gomock.Controller) *MockRefreshTokenStore {
	mock := &MockRefreshTokenStore{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRefreshTokenStore) EXPECT() *MockRefreshTokenStoreMockRecorder {
	return m.recorder
}

// Set mocks base method
func (m *MockRefreshTokenStore) Set(token *RefreshToken) error {
	ret := m.ctrl.Call(m, "Set", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockRefreshTokenStoreMockRecorder) Set(token interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRefreshTokenStore)(nil).Set), token)
}

// Get mocks base method
func (m *MockRefreshTokenStore) Get(token string) (*RefreshToken, error) {
	ret := m.ctrl.Call(m, "Get", token)
	ret0, _ := ret[0].(*RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRefreshTokenStoreMockRecorder) Get(token interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRefreshTokenStore)(nil).Get), token)
}

// Delete mocks base method
func (m *MockRefreshTokenStore) Delete(token string) error {
	ret := m.ctrl.Call(m, "Delete", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRefreshTokenStoreMockRecorder) Delete(token interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefreshTokenStore)(nil).Delete), token)
}
